import {
  defaultThemeFamily,
  defaultThemeMode,
  themeDefinitions,
  themeModes,
} from '../src/themes/index.js';
import { validateThemeDefinitions } from '../src/themes/schema.js';

export function formatTokens(tokens) {
  return Object.entries(tokens)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join('\n');
}

export function selectorFor(theme, mode) {
  const themeId = `${theme.id}-${mode}`;
  const selectors = [];

  if (theme.id === defaultThemeFamily && mode === defaultThemeMode) {
    selectors.push(':root');
    selectors.push(`:root[data-theme='${themeId}']`);
  } else if (theme.id === defaultThemeFamily && mode === 'light') {
    selectors.push(":root[data-theme='light']");
    selectors.push(`:root[data-theme='${themeId}']`);
  } else {
    selectors.push(`:root[data-theme='${themeId}']`);
  }

  return selectors.join(',\n');
}

export function renderThemeBlock(theme, mode) {
  const config = theme.modes[mode];
  return `${selectorFor(theme, mode)} {\n  color-scheme: ${config.colorScheme};\n${formatTokens(config.tokens)}\n}`;
}

export function renderThemeCss({ definitions = themeDefinitions, modes = themeModes } = {}) {
  const errors = validateThemeDefinitions(definitions, modes);
  if (errors.length > 0) {
    throw new Error(`Theme validation failed:\n${errors.map((error) => `- ${error}`).join('\n')}`);
  }

  return `/* This file is generated by scripts/generate-theme-css.mjs. Do not edit directly.\n   Edit src/themes/*.js instead. */\n\n${definitions
    .flatMap((theme) => modes.map(({ id: mode }) => renderThemeBlock(theme, mode)))
    .join('\n\n')}\n`;
}
